---
- name: create project dir
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ workspace }}"

- stat: path={{ workspace }}/docker-compose.yml
  register: docker_compose_file

- name: stop service
  docker_service:
    project_src: "{{ workspace }}"
    state: absent
  when: docker_compose_file.stat.exists == True
  ignore_errors: True

- name: remove compose file
  file:
    path: "{{ workspace }}"
    state: absent
  when: docker_compose_file.stat.exists == True

- name: create group
  group:
    name: "{{ group_name }}"
    state: present

- name: create user
  user:
    name: "{{ user_name }}"
    group: "{{ group_name }}"
    state: present

- name: create workspace
  file:
    path: "{{ item }}"
    owner: "{{ user_name }}"
    group: "{{ group_name }}"
    state: directory
  with_items:
    - "{{ workspace }}"

- name: copy compose file
  template:
    src: "docker-compose.yml"
    dest: "{{ workspace }}/docker-compose.yml"
    owner: "{{ user_name }}"
    group: "{{ group_name }}"

- name: start service
  docker_service:
    project_src: "{{ workspace }}"
    scale:
      chrome: "{{ selenium_chrome_nodes_count }}"
      firefox: "{{ selenium_firefox_nodes_count }}"