---
- name: start selenium grid
  hosts: [selenium-nodes]

  become: true
  become_method: sudo

  vars:
    selenium_chrome_nodes_count: 8
    selenium_firefox_nodes_count: 0

  vars_prompt:
    - name: "selenium_hub_host"
      prompt: "where is selenium hub?"
      private: no

  roles:
    - selenium-nodes