version: '2'

networks:
  selenium-nodes:
    driver: bridge

services:
{% if selenium_chrome_nodes_count != 0 %}

  chrome:
    image: "{{ docker_selenium_chrome_image }}:{{ selenium_version }}"
    networks:
      - selenium-nodes
    environment:
      HUB_PORT_4444_TCP_ADDR: {{ selenium_hub_host }}
      HUB_PORT_4444_TCP_PORT: {{ selenium_hub_port }}

{% endif %}
{% if selenium_firefox_nodes_count != 0 %}

  firefox:
    image: "{{ docker_selenium_firefox_image }}:{{ selenium_version }}"
    networks:
      - selenium-nodes
    environment:
      HUB_PORT_4444_TCP_ADDR: {{ selenium_hub_host }}
      HUB_PORT_4444_TCP_PORT: {{ selenium_hub_port }}

{% endif %}