version: '2'

networks:
  selenium-hub:
    driver: bridge

services:
  hub:
    image: "{{ docker_selenium_hub_image }}:{{ selenium_version }}"
    ports:
      - 4444:4444
    networks:
      - selenium-hub