version: '2'

networks:
  private:
    driver: bridge

services:
  hub:
    image: "{{ docker_selenium_hub_image }}:{{ selenium_version }}"
    ports:
      - 4444:4444
    networks:
      - private

{% if selenium_chrome_nodes_count != 0 %}

  chrome:
    image: "{{ docker_selenium_chrome_image }}:{{ selenium_version }}"
    networks:
      - private
    depends_on:
      - hub
    environment:
      HUB_PORT_4444_TCP_ADDR: hub

{% endif %}
{% if selenium_firefox_nodes_count != 0 %}

  firefox:
    image: "{{ docker_selenium_firefox_image }}:{{ selenium_version }}"
    networks:
      - private
    depends_on:
      - hub
    environment:
      HUB_PORT_4444_TCP_ADDR: hub

{% endif %}